# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IZg7qgkP0YDEQinpFpqPocL1bFnZ_KGO
"""

import pandas as pd

import numpy as np
import pickle

df1 = pd.read_csv('tech.csv', on_bad_lines='skip', engine='python')

df1.info()

df1 = df1.dropna()

df1.dropna()

df1['jobdescription'].head()

from sklearn.feature_extraction.text import TfidfVectorizer

tdif = TfidfVectorizer()

df1['jobdescription'] = df1['jobdescription'].fillna('')

tdif_matrix = tdif.fit_transform(df1['jobdescription'])
tdif_matrix.shape

from sklearn.metrics.pairwise import sigmoid_kernel
cosine_sim = sigmoid_kernel(tdif_matrix, tdif_matrix)
indices = pd.Series(df1.index, index=df1['jobtitle']).drop_duplicates()

def get_recommendations(title, cosine_sim = cosine_sim):
  idx = indices[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda X:X[1], reverse=True)
  sim_scores = sim_scores[1:16]
  tech_indices = [i[0] for i in sim_scores]
  return df1['jobtitle'].iloc[tech_indices]

new1 = df1[['jobtitle', 'jobdescription']]

df1.tail()

new1.to_csv('new.csv')

pickle.dump(new1, open('job_list.pkl','wb'))
pickle.dump(cosine_sim, open('similarity.pkl','wb'))